export const FETCH_INSTRUCTOR_START = 'FETCH_INSTRUCTOR_START'
export const FETCH_INSTRUCTOR_FINISH = 'FETCH_INSTRUCTOR_FINISH'
export const FETCH_INSTRUCTOR_RECEIVED = 'FETCH_INSTRUCTOR_RECEIVED'

export const FETCH_LOGIN_START = 'FETCH_LOGIN_START'
export const FETCH_LOGIN_FINISH = 'FETCH_LOGIN_FINISH'
export const FETCH_LOGIN_RECIEVED = 'FETCH_LOGIN_RECIEVED'